#! /bin/bash

autoload -U compinit && compinit
autoload -U bashcompinit && bashcompinit

_predix_cli_zsh_autocomplete() {
  local cur opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
  local IFS=$'\n'
  COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
  return 0
}

complete -F _predix_cli_zsh_autocomplete predix
complete -F _predix_cli_zsh_autocomplete px
